### ISSUE TITLE
SIMD as separate package

### ISSUE THREAD

**Issue by krux02** [jcosborn/qex#3]
Well to be honest I have no idea what "Quantum EXpressions lattice field theory" is. But the SIMD package is pretty useful for me. Can you make the SIMD instructions a separate package pretty please :smile:  

I would like to eventually improve this glm port here https://github.com/stavenko/nim-glm with SIMD instructions.

**Comment by jcosborn** [comment]
I've started splitting it out as https://github.com/nimlibs/simdX86.
Let me know if it is missing anything important.

**Comment by krux02** [comment]
Well I realized that integrating SIMD in my glm port isn't as easy as I thought. But I am closing this. If I have further issues I will open them in the simd project.
